name: cowsay1

on: 
    push:

    workflow_dispatch:

jobs:
  dragon_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, iam Chicken....BakBaaaaK" >> chicken.txt

      - name: read dragon
        run: cat dragon.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3

        with:
          name: chicken-file
          path: chicken.txt
      
      - name: read readme file
        run: ls
